#+startup: beamer

* PMX population solvers @@latex:\\ \footnotesize{Yi Zhang}@@

** PMX population solvers
   :PROPERTIES:
   :BEAMER_envargs: [t]
   :END:
| Single ODE system | ODE group               |
|-------------------+-------------------------|
| =pmx_solve_rk45=  | =pmx_solve_group_rk45=  |
| =pmx_solve_bdf=   | =pmx_solve_group_bdf=   |
| =pmx_solve_adams= | =pmx_solve_group_adams= |

*** Individual solvers                                        :BMCOL:B_block:
    :PROPERTIES:
    :BEAMER_col: 0.45
    :BEAMER_env: block
    :END:
#+begin_src stan
  matrix
  pmx_solve_bdf(f, int nCmt,
    real[] time, real[] amt,
    real[] rate, real[] ii,
    int[] evid, int[] cmt,
    real[] addl, int[] ss,
    real[] theta, real[] biovar,
    real[] tlag, real rel_tol,
    real abs_tol, int max_step);
#+end_src

*** Population solvers                                        :BMCOL:B_block:
    :PROPERTIES:
    :BEAMER_col: 0.55
    :BEAMER_env: block
    :END:
#+begin_src stan
  matrix
  pmx_solve_group_bdf(f, int nCmt,
    int[] len, real[] time,
    real[] amt, real[] rate,
    real[] ii, int[] evid,
    int[] cmt, real[] addl,
    int[] ss, real[ , ] theta,
    real[ , ] biovar, real[ , ] tlag,
    real rel_tol, real abs_tol,
    int max_step);
#+end_src


** PMX population solvers
#+begin_src stan
  matrix
  pmx_solve_group_bdf(f, int nCmt, int[] len, real[] time, real[] amt, real[] rate, real[] ii, int[] evid, int[] cmt, real[] addl, int[] ss, real[,] theta, real[,] biovar, real[,] tlag, real rel_tol, real abs_tol, int max_step);
#+end_src

*** 
#+caption: arguments and output of =pmx_solve_group_xxx=
#+attr_latex: :width 0.6\textwidth
[[./figures/group_solver_args.pdf]]

** Exercise
   :PROPERTIES:
   :BEAMER_envargs: [t]
   :END:
  We analyze the time to the first grade 2+ peripheral neuropathy
  (PN) event in patients treated with an antibody-drug conjugate (ADC) delivering monomethyl auristatin E
  (MMAE). We will simulate and analyze data using a simplified version of the
  model reported in cite:lu_time--event_2017.
  - Fauxlatuzumab vedotin 1.2 mg/kg IV boluses q3w $\times$ 6 does.
  - 19 patients with 6 right-censored (simulated data).
***  Model scheme                                      :BMCOL:B_block:
    :PROPERTIES:
    :BEAMER_col: 0.3
    :BEAMER_env: block
    :END:
#+attr_latex: :width 0.9\columnwidth
    [[../../examples/ttpn2/lu2017Model.pdf]]
***  Note                                                     :BMCOL:B_block:
    :PROPERTIES:
    :BEAMER_col: 0.7
    :BEAMER_env: block
    :END:
  - To keep things simpler, we use the simulated individual CL and V values, and only model PD part of the problem.
  - PN hazard is substantially delayed relative to PK exposure.
  - Hazard increases over time to an extent not completely described by PK.

** Exercise
Likelihood for time to first PN $\ge$ 2 event in the $i^{th}$ patient:
  \begin{align*}
  \lefteqn{L\left(\theta | t_{\text{PN},i}, \text{censor}_i, X_i\right)} \\
    &= \left\{ \begin{array}{ll}
       h_i\left(t_{\text{PN},i} | \theta, X_i\right) e^{-\int_0^{t_{\text{PN},i}} h_i\left(u | \theta, X_i\right) du}, &
      \text{censor}_i = 0 \\
       e^{-\int_0^{t_{\text{PN},i}} h_i\left(u | \theta, X_i\right) du}, &
       \text{censor}_i = 1
  \end{array} \right.
  \end{align*}
  where
  \begin{align*}
    t_{\text{PN}} &\equiv \text{time to first PN $\ge$ 2 or right
      censoring event} \\
  \theta &\equiv \text{model parameters} \\
  X &\equiv \text{independent variables / covariates} \\
  \text{censor} &\equiv \left\{ \begin{array}{ll}
      1, & \text{PN $\ge$ 2 event is right censored} \\
      0, & \text{PN $\ge$ 2 event is observed} 
  \end{array} \right.
 \end{align*}
One can see the expression
\begin{equation*}
  e^{-\int_0^{t_{\text{PN},i}} h_i\left(u | \theta, X_i\right) du}
\end{equation*}
as the survival function at time $t$.

** Exercise
Hazard of PN grade 2+ based on the Weibull distribution,
with drug effect proportional to effect site concentration of MMAE:
\begin{align*}
  h_j(t) &= \beta E_{\text{drug}j}(t)^\beta t^{(\beta - 1)} \\
  E_{\text{drug}j}(t) &= \alpha c_{ej}(t) \\
  c^\prime_{ej}(t) &= k_{e0} \left(c_j(t) - c_{ej}(t)\right).
\end{align*}

Overall ODE system including integration of the hazard function:
\begin{align}
  x_1^\prime &= -\frac{CL}{V} x_1 \\
  x_2^\prime &= k_{e0} \left(\frac{x_1}{V} - x_2\right) \\
  x_3^\prime &= h(t)
  \end{align}
where $x_2(t) = c_e(t)$ and $x_3(t) = \int_0^t h(u) du$ aka cumulative hazard.

** Exercise
*** "just walk in a minute ago, literally" mode
   Apply =pmx_solve_group_rk45= function
*** Intermediate mode
   Code =pmx_solve_group_rk45= function and its args. Use input data file =ttp2n.data2.R= as hint.
*** hard mode
  Code ODE, =pmx_solve_group_rk45= function and its args,
  and the likelihood for harzard and censor event. Use input
  data file =ttp2n.data2.R= and =model= block as hint.
*** "why bother" mode

** Exercise
*** Edit/Add =cmdstan/make/local=
#+BEGIN_SRC sh
  TORSTEN_MPI = 1         # flag on torsten's MPI solvers
  CXXFLAGS += -isystem /usr/local/include # path to MPI library's headers
#+END_SRC
*** Build in =cmdstan=
#+BEGIN_SRC sh
  make ../example-models/ttpn2/ttpn2_group
#+END_SRC
*** Run
#+BEGIN_SRC sh
mpiexec -n 4 -l ttpn2_group sample num_warmup=500 num_samples=500 data file=ttpn2.data2.R init=ttpn2.init.R
#+END_SRC

** Exercise
- The parallel performance is not optimal, why?
- Can you do it using Stan's =map_rect=? 

** Reference
\bibliography{ttpn2}
bibliographystyle:plain
